name: 'core-cloud-add-customer-action'
description: 'GitHub Action to add a customer to the Core Cloud LZA config'
author: 'ukhomeoffice'

# Define your inputs here.
inputs:
  github_token:
    description: 'Github API token'
    required: true
  file_path:
    description: 'Relative path to the accounts-config.yaml file'
    required: true
  customer_id:
    description: 'Unique name for the customer'
    required: true
  spoc_email:
    description: 'Single point of contact email address'
    required: true
  environments:
    description: 'CSV list of OUs to create accounts under'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
