name: 'core-cloud-add-customer-action'
description: 'GitHub Action to add a customer to the Core Cloud LZA config'
author: 'ukhomeoffice'

inputs:
  folder_path:
    description: 'Relative path to the folder containing the files'
    required: true
  customer_id:
    description: 'Unique name for the customer'
    required: true
  spoc_email:
    description: 'Single point of contact email address'
    required: true
  organisational_units:
    description: 'CSV list of OUs to create accounts under'
    required: true

runs:
  using: node20
  main: dist/index.js
