name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    env:
      FOLDER_PATH: __tests__/files/tmp
      ACCOUNTS_FILE_PATH: ${{ FOLDER_PATH }}/accounts-config.yaml
      IAM_FILE_PATH: ${{ FOLDER_PATH }}/iam-config.yaml

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Files
        env:
          EMPTY_ACCOUNTS_FILE_PATH: __tests__/files/account/empty.yaml
          EMPTY_IAM_FILE_PATH: __tests__/files/iam/empty.yaml
        run: |
          mkdir -p $(dirname ${{ FOLDER_PATH }}) 
          cp ${{ EMPTY_ACCOUNTS_FILE_PATH }} ${{ env.ACCOUNTS_FILE_PATH }}
          cp ${{ EMPTY_IAM_FILE_PATH }} ${{ env.IAM_FILE_PATH }}

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          folder_path: ${{ env.FOLDER_PATH }}
          customer_id: test
          spoc_email: test@example.com
          organisational_units: test

      - name: Check diff output
        run: |
          git diff --name-only ${{ env.ACCOUNTS_FILE_PATH }} | grep ${{ env.ACCOUNTS_FILE_PATH }} || exit 1
          git diff --name-only ${{ env.IAM_FILE_PATH }} | grep ${{ env.IAM_FILE_PATH }} || exit 1
